SOURCE_BUCKET = 'datasets.mlops'
DEST_BUCKET = 'datasets.mlops'
RAW_FILE_KEY = 'raw/OpenStack_2k.log_structured.csv'
SILVER_FILE_NAME = 'OpenStack_cleaned.csv'
SILVER_FILE_KEY = 'silver/OpenStack_cleaned.csv'
GOLD_FILE_KEY = 'gold/OpenStack_cleaned.csv'
AWS_REGION = 'us-east-1'
