airflow:
  extraPipPackages:
    - -r /opt/airflow/dags/code/dags/requirements.txt
dags:
  gitSync:
    enabled: true
    repo: https://github.com/cohort-4-group-1/capstone_rca_genai.git
    branch: sujit-eda         
    subPath: "code/dags"          
    depth: 1 
web:
  dagMountPath: /opt/airflow/dags

worker:
  dagMountPath: /opt/airflow/dags

