
worker:
  name: worker
  image:
    repository: sujittah/dask-custom
    tag: 2023.12.1
    pullPolicy: Always  
  serviceAccountName: dask-access
  serviceAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::682033474520:role/iisc-capstone-rca-dask-s3-access  

scheduler:
  name: scheduler
  image:
    repository: sujittah/dask-custom
    tag: 2023.12.1
    pullPolicy: Always
  
