global:
  region: us-east-1
  namespace: api
  serviceAccount:
    name: logbert-s3-access
    roleArn: arn:aws:iam::141134438799:role/iisc-capstone-rca-model-s3-access

api:
  image:
    repository: sujittah/logbert-api
    tag: latest
  service:
    port: 9000

