global:
  region: us-east-1
  namespace: api
  serviceAccount:
    name: logbert-s3-access
    roleArn: arn:aws:iam::141134438799:role/iisc-capstone-rca-model-s3-access

api:
  image: sujittah/logbert-api
  service:
    port: 9000
  env:
    OTEL_EXPORTER_OTLP_ENDPOINT: ""
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ""
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ""
    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: ""

