FROM python:3.10-slim


# Set the working directory in the container
WORKDIR /code


# Copy the requirements file into the container
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir \
    gradio \
    request



# Copy the rest of the application code into the container
COPY ./app /code/app

# Expose the port the app runs on
EXPOSE 7860

ENV GRADIO_SERVER_NAME="0.0.0.0"

WORKDIR /code/app

# Command to run the Gradio app
CMD ["python", "app.py"]