apiVersion: apps/v1
kind: Deployment
metadata:
  name: logbert-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logbert-api
  template:
    metadata:
      labels:
        app: logbert-api
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
        - name: api
          image: "{{ .Values.api.image}}"
          pullPolicy: Always
          ports:
            - containerPort: {{ .Values.api.service.port }}
          env:
            - name: AWS_REGION
              value: {{ .Values.global.region }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.api.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.api.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: {{ .Values.api.env.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: {{ .Values.api.env.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT | quote }}
