apiVersion: v1
kind: Service
metadata:
  name: logbert-api
spec:
  type: ClusterIP
  selector:
    app: logbert-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
